### ISSUE TITLE
Duplicate definition for unknown

### ISSUE THREAD

**Issue by fcatt** [armel/uv-k5-chirp-driver#15]
Probablement pas grand chose, mais lorsque je lance CHIRP 20240706 avec le driver uvk5_egzumer_f4hwn_ver_3_0_1.py, une ligne d'erreur est générée (mais tout a l'air de fonctionner normalement):

```
$ flatpak run com.danplanet.chirp.chirp_next
ERROR: Duplicate definition for unknown on line 163:     unknown:1;; renaming to unknown_000f47 (previous definition line 136)
```

Je pense que les vrais numéros de ligne dans uvk5_egzumer_f4hwn_ver_3_0_1.py sont 199 et 226 (disclaimer: je n'y connais pas grand chose en Python).

**Comment by joc2** [comment]
Effectivement il y a duplication, c'est la depuis le debut de egzumer,...
je vais les renomer autrement pour ne plus avoir cette ligne d'erreur, mais ce sont des bits memoire non utiliser, donc pas d'effect
Merci pour l'info
