### ISSUE TITLE
configuring scanlist participation via chirp

### ISSUE THREAD

**Issue by SutliffeProductions** [armel/uv-k5-chirp-driver#16]
Hi, Is it possible to add channels to scanlists via Chirp? I am using the module and such, but I can't seem to find a way to do it without doing it manually on the radio, which is a pain when having to do it 100+ times.

Am i being an idiot? 
Thanks,

**Comment by armel** [comment]
Hi,

Yes, of course. See screenshot in attachement. 

Armel.
![chirp](https://github.com/user-attachments/assets/50a8a4de-e54d-41ab-9dbc-582cc891755c)

**Comment by SutliffeProductions** [comment]
ahh knew there was something im missing, thanks so much, I feel like an idiot now
