### ISSUE TITLE
Scan List selection in CHIRP

### ISSUE THREAD

**Issue by MrMinecraft97** [armel/uv-k5-chirp-driver#17]
Feature suggestion:

Add a menu option in CHIRP similar to the current Skip column to designate memory channels to be in a specific scan list(s).

Maybe even as simple as (for each memory) having a column for each scanlist (1, 2, and 3) and just having a Yes or No as to whether or not that memory is in that list.

Could also have a way to be in multiple lists easily like a list 4 is actually in both 1 and 2, etc.

Thanks

**Comment by armel** [comment]
Take a look here... https://github.com/armel/uv-k5-chirp-driver/issues/16

**Comment by MrMinecraft97** [comment]
Ah ha! Thank you!

Never saw that menu!
