### ISSUE TITLE
missing items from right click properties options

### ISSUE THREAD

**Issue by sparky93a** [armel/uv-k5-chirp-driver#31]
Hi,
when I select several or all lines of memories in chirp, you can right click then properties and the new box is edit details for xx memorys.
this you can bulk change power levels or steps etc.

but there are missing items here, i wanted to block change memories into various groups of the scan lists 1 2 or 3 in one go.

kind regards.
![Untitled](https://github.com/user-attachments/assets/abf9afb9-d8fc-4829-b733-226acf591867)

**Comment by armel** [comment]
Click on extra tab...
![379920802-abf9afb9-d8fc-4829-b733-226acf591867](https://github.com/user-attachments/assets/7d786ee5-b144-42e4-b763-6989736e2651)
