### ISSUE TITLE
Pour Armel

### ISSUE THREAD

**Issue by ChrisWDC07** [armel/uv-k5-chirp-driver#4]
Bonjour Armel, 
Merci d'avoir répondu aussi rapidement à mon commentaire, comme tu vois j'ai suivi tes conseils et utilisé -issuse- 
Donc merci encore pour tes réponses, pour ce qui est de la  3ème liste je comprends très bien ton point de vue, c'était juste une suggestion mais intéressante pour beaucoup je pense, effectivement cela donnerai du boulot au niveau de CHIRP mais je pense pas indispensable de le faire étant donné que cela eserait gérable sur le pocket directement et seul les utilisateurs aguérits utiliserai cette fonction. 
Pour les 2 versions, n'étant pas développeur (je n'ai écrit que quelques lignes de code en basic du temps du TRS80) je pensai que les modules broadcast ou spectrum pouvaient simplement être  ajouté ou supprimer lors de la compilation ce qui permettrait le gain de place rapide pour d'autres ajouts. Une fois de plus n'étant pas programmeur, tu es le seul "maître à bord" 
Question : pour accèder au scan touche 4 longue pourquoi pour le spectrum la touche 5 longue ne fonctionne pas et il faut passer par F 5 alors que la 0 longue fonctionne également. Normal, bug, ou impossibilité.
73 Christian

**Comment by armel** [comment]
Bonjour Christian,

La réponse est dans la doc. L'appui long sur 5 est déjà [affecté](https://github.com/egzumer/uv-k5-firmware-custom/wiki/Button-functions#5-noaa).

73'

Armel F4HWN.
