### ISSUE TITLE
Bug 2.3 >> Chirp

### ISSUE THREAD

**Issue by Chatdurail** [armel/uv-k5-chirp-driver#6]
Salut Armel, 

J'ai remarqué depuis le passage en 2.3 sur mon UV K5(8) et UV 5R quansheng l'impossibilité d'accéder au préférences sur CHIRP (dernière version à jour)

![Capture d’écran 2024-03-17 à 15 42 10](https://github.com/armel/uv-k5-chirp-driver/assets/163455599/bbfda016-2656-4425-96ff-a0eb9cce55fb)

j'ai rétrogradé mon UVK5 en 2.2 et là pas de soucis, par contre 2.3 impossible 

Cependant la programmation des canaux et envoi sur la radio RAS

Je tourne CHIRP sur mac OK 

Bien à toi 

Alex

**Comment by armel** [comment]
Bonjour Alex,

Ok. Quelle version du driver ?
Je viens de tenter avec la dernière version 2.2.2 datant d'il y a [4 jours](https://github.com/armel/uv-k5-chirp-driver/releases/tag/2.2.2). Et aucun problème. Je suis sous Macos également ;)

Armel F4HWN.

**Comment by Chatdurail** [comment]
J'avais 2 jours d'avance, j'avais pas ton dernier Python, le 2.2.2 fonctionne bien 

Désolé de t'avoir embêter et merci pour ton gros boulot

Bien à toi

**Comment by armel** [comment]
Aucun problème Alex, ce n'est rien.
En cas de doute, toujours vérifier s'il n'y a pas une version plus récente du driver. 
Mon firmware est expérimental avec des évolutions d'une version à l'autre. Le driver évolue en fonction :)
Je cloture l'issue.

Armel F4HWN.
