### ISSUE TITLE
Méthode trouvée pour que Chirp fonctionne avec ton firmware 

### ISSUE THREAD

**Issue by sunplop-git** [armel/uv-k5-chirp-driver#7]
Bonjour Armel,

J'ai réussi à faire fonctionner chirp avec ton firmware 2.4 en modifiant un fichier .py de la version Egzumer. qui est pris en en extension de Chirp...

La méthode est décrite sur mon site où il y a pas mal d'infos glanées sur l'UV-K5: http://f80431.free.fr/?cat=20

Si tu veux des infos complémentaires, tu peux me contacter par mail: f80431@free.fr

73's et à bientôt, 
Daniel.

**Comment by armel** [comment]
Bonjour Daniel,

Pourquoi faire puisque mon firmware dispose de son propre driver Chirp ?

Je ne comprends pas trop la démarche 🤔

En plus, tu postes cette issue précisément sur le repository du driver Chirp dédié à mon firmware et qui existe depuis déjà quelques semaines. J'ai même fait une [video](https://www.youtube.com/watch?v=02T2ODufZOA&t=3s&ab_channel=F4HWNArmel) dessus sur ma chaine  😉

J'ai loupé un truc ? 

Tu trouveras même un driver francisé en téléchargement 🤭

73'

Armel F4HWN.
