### ISSUE TITLE
The driver does not display Bandwidth

### ISSUE THREAD

**Issue by vita5656** [armel/uv-k5-chirp-driver#9]
The driver does not display Bandwidth and there is no option to set Bandwidth. :-(
Normally it is in the properties on the "Extra" tab
I tried version 2.5 and 2.6.

**Comment by armel** [comment]
You're probably referring to the Mode column: FM (FM WIDE), NFM (FM Narrow), AM, etc.

**Comment by vita5656** [comment]
OK, your driver has a slightly different structure. I assume NFM = 12.5 kHz, FM = 25 kHz. And similarly for AM and NAM.
So it's solved. Thank you. Very nice firmware.

**Comment by vita5656** [comment]
It was a misunderstanding.
